component_depth: 1
languages:
- php
production:
	exclude:
		- .*Test.php
exclude:
	- /ow_includes
	- /ow_install
	- /ow_libraries
	- /ow_log
	- /ow_pluginfiles
	- /ow_plugins
	- /ow_static
	- /ow_system_plugins
	- /ow_themes
	- /ow_updates
	- /ow_userfiles
test:
	include:
		- /ow_unittest
		- .*Test.php