<?php
/**
 * User: Issa Moradnejad
 * Date: 2016/09/11
 */

class slideshowTest extends IISTestUtilites
{
    private $TEST_USER1_NAME = "user1";
    private $TEST_USER2_NAME = "user2";
    private $TEST_PASSWORD = '12345';

    private $userService;
    private $user1,$user2;

    private function echoText($text, $bounding_box=false)
    {
        if ($bounding_box) {
            echo "-----------------------------ISSA------------------------------------\n";
            echo "$text\n";
            echo "---------------------------------------------------------------------\n";
        }else
            echo "==========ISSA:==>$text\n";
    }
    private function hide_element($className){
        try {
            $this->execute(array(
                'script' => "document.getElementsByClassName('" . $className . "')[0].style.visibility = 'hidden';",
                'args' => array()
            ));
        }catch(Exception $ex){
            $this->echoText('hide_element_error:'.$ex);
        }
    }

    protected function setUp()
    {
        $this->setBrowser('firefox');
        $this->setBrowserUrl(OW_URL_HOME);
        $this->userService = BOL_UserService::getInstance();
        $accountType = BOL_QuestionService::getInstance()->getDefaultAccountType()->name;

        IISSecurityProvider::createUser($this->TEST_USER1_NAME,"user1@gmail.com",$this->TEST_PASSWORD,"1969/3/21","1",$accountType);
        IISSecurityProvider::createUser($this->TEST_USER2_NAME,"user2@gmail.com",$this->TEST_PASSWORD,"1969/3/21","1",$accountType);
        $this->user1 = BOL_UserService::getInstance()->findByUsername($this->TEST_USER1_NAME);
        $this->user2 = BOL_UserService::getInstance()->findByUsername($this->TEST_USER2_NAME);

    }

    public function setUpPage()
    {
        parent::setUpPage(); // TODO: Change the autogenerated stub
        $this->timeouts()->implicitWait(15000);
    }

    public function testSlideshow()
    {
        //----SCENARIO 1 -
        // User1 uploads a new photo
        // User1 goes to photos and clicks on the latest photo
        // User1 can see slideshow

        $test_caption = "slideshowTest-testSlideshow";
        //$this->echoText($test_caption);
        $CURRENT_SESSIONS = $this->prepareSession();
        $CURRENT_SESSIONS->currentWindow()->maximize();

        $this->url(OW_URL_HOME . "dashboard");
        $sessionId = $CURRENT_SESSIONS->cookie()->get(OW_Session::getInstance()->getName());
        $sessionId = str_replace('%2C', ',', $sessionId);
        //----------USER1
        $this->sign_in($this->user1->getUsername(),$this->TEST_PASSWORD,true,true,$sessionId);
        try {
            //POST IMAGE
            $this->url('dashboard');
            $this->byName('status')->click();
            $this->byName('status')->value($test_caption);

            $newsFeedForm = $this->byName('newsfeed_update_status');
            $attachment = $newsFeedForm->byClassName('mlt_file_input');
            $file_path = getcwd().DS. $test_caption . '.png'; //"D:\\programmer.jpg"
            //$this->echoText($file_path);
            file_put_contents($file_path, $this->currentScreenshot());
            $attachment->value($file_path);
            $this->waitUntilElementLoaded("byXPath",'//input[@name="attachment" and @value != ""]');

            $statusPrivacy = $this->byName('statusPrivacy');
            $statusPrivacy->byXPath('option[@value="everybody"]')->click();//only_for_me, everybody, friends_only

            $this->byXPath('//input[@name="save"]')->click();
            unlink($file_path);
        }catch (Exception $ex) {
            $this->echoText($ex,true);
            if (getenv("SNAPSHOT_DIR"))
                file_put_contents(getenv("SNAPSHOT_DIR") . $test_caption . '.png', $this->currentScreenshot());
            $this->assertTrue(false);
            return;
        }

        try {
            //check slideshow
            $this->url('photo/viewlist/latest');
            sleep(1);
            $this->byClassName("ow_photo_pint_album")->click();
            sleep(1);
            $res = $this->checkIfXPathExists('//*[@class="floatbox_body"]//*[@class="ow_photoview_info"]');
            $this->assertTrue($res);
        } catch (Exception $ex) {
            $this->echoText($ex, true);
            if (getenv("SNAPSHOT_DIR"))
                file_put_contents(getenv("SNAPSHOT_DIR") . $test_caption . '.png', $this->currentScreenshot());
            $this->assertTrue(false);
        }
    }


    public function tearDown()
    {
        //delete users
        $questionDao = BOL_QuestionService::getInstance();
        $userDao = BOL_UserDao::getInstance();

        $questionDao->deleteQuestionDataByUserId($this->user1->getId());
        $userDao->deleteById($this->user1->getId());

        $questionDao->deleteQuestionDataByUserId($this->user2->getId());
        $userDao->deleteById($this->user2->getId());
    }
}