<?php
/**
 * User: Issa Moradnejad
 * Date: 2016/07/10
 */

class linkCheckingTest extends IISTestUtilites
{
    private $TEST_USER1_NAME = "user1";
    private $TEST_PASSWORD = '12345';

    private $userService;
    private $user1;

    private $questionService;

    private function echoText($text, $bounding_box=false)
    {
        if ($bounding_box) {
            echo "-----------------------------ISSA------------------------------------\n";
            echo "$text\n";
            echo "---------------------------------------------------------------------\n";
        }else
            echo "==========ISSA:==>$text\n";
    }


    protected function setUp()
    {
        $this->setBrowser('firefox');
        $this->setBrowserUrl(OW_URL_HOME);
        $this->userService = BOL_UserService::getInstance();
        if($this->userService->isExistUserName($this->TEST_USER1_NAME)) { // delete if already exists
            $this->user1 = $this->userService->findByUsername($this->TEST_USER1_NAME);
            $this->userService->deleteUser($this->user1->getId());
        }
        $this->user1 = $this->userService->createUser($this->TEST_USER1_NAME, $this->TEST_PASSWORD, "user1@gmail.com", null, true);
        // set some info to users
        $this->questionService = BOL_QuestionService::getInstance();
        $data = array();
        $data['username'] = $this->user1->getUsername();
        $data['email'] = $this->user1->getEmail();
        $data['realname'] = $this->user1->getUsername();
        $data['sex'] = "1";
        $data['birthdate'] = "1987/3/21";
        $this->questionService->saveQuestionsData($data, $this->user1->getId());
    }

    public function setUpPage()
    {
        parent::setUpPage(); // TODO: Change the autogenerated stub
        $this->timeouts()->implicitWait(15000);
    }
    public function checkAllLinksInPage($start_url){
        $error_count = 0;
        $selenium_error_count = 0;
        $total_count = 0;
        $this->url($start_url);
        $i = 0;
        while(true){
            $i++;
            $p = '(//a[@href])['.$i.']';
            try{
                $tag = $this->byXPath($p);
                if(!$tag->displayed())
                    continue;
                $href = $tag->attribute("href");
            }
            catch(Exception $ex){
                break;
            }
            if(strpos($href,"http")===0 && strpos($href, OW_URL_HOME)===false) {// check only internal links
                //echo $href . "\n";
                continue;
            }

            $selenium_error = false;
            try {
                $tag->click();
            }catch(Exception $ex){
                $selenium_error = true;
                $selenium_error_count++;
                $this->echoText("SELENIUM ERROR:".$href);
            }

            if(!$selenium_error) {
                if($this->checkIfXPathExists('//body[contains(@class, "base_page404")]')) {
                    $this->echoText("ERROR404:".$href);
                    $error_count++;
                }else if($this->checkIfXPathExists('//*[text()[contains(.,"Error 500")]]')) {
                    $this->echoText("ERROR500:".$href);
                    $error_count++;
                }
            }
            $total_count++;
            $this->url($start_url);
        }
        if($error_count!==0)
            $this->echoText("ERRORS FOR $start_url: $error_count(+$selenium_error_count selenium errors) of $total_count urls.");
        return ($error_count==0);
    }
    public function checkAllLinks($start_url, $CURRENT_SESSIONS, $checkLoggedOut)
    {
        if(true) {
            //----------USER LOGGED OUT
            $ret1 = true;
            if($checkLoggedOut)
                $ret1 = $this->checkAllLinksInPage($start_url);
            //----------USER LOGGED IN
            $sessionId = $CURRENT_SESSIONS->cookie()->get(OW_Session::getInstance()->getName());
            $sessionId = str_replace('%2C', ',', $sessionId); // took 2 hours to detect  '/^[-,a-zA-Z0-9]{1,128}$/'
            $this->sign_in($this->user1->getUsername(),$this->TEST_PASSWORD,true,true,$sessionId);
            $ret2 = $this->checkAllLinksInPage($start_url);
            $this->url(OW_URL_HOME .'sign-out');

            return ($ret1&&$ret2);
        }
    }

    public function testLinksHomepage()
    {
        if(true) {
            $test_caption = "linkCheckingTest-testLinksHomepage";
            //$this->echoText($test_caption);
            $this->url(OW_URL_HOME); //required for sessions
            $CURRENT_SESSIONS = $this->prepareSession();
            $CURRENT_SESSIONS->currentWindow()->maximize();
            $start_url = OW_URL_HOME ."";
            $ret = $this->checkAllLinks($start_url, $CURRENT_SESSIONS, true);
            $this->assertTrue($ret);
        }
    }

    public function testLinksDashboard()
    {
        if(true) {
            $test_caption = "linkCheckingTest-testLinksDashboard";
            //$this->echoText($test_caption);
            $this->url(OW_URL_HOME); //required for sessions
            $CURRENT_SESSIONS = $this->prepareSession();
            $CURRENT_SESSIONS->currentWindow()->maximize();
            $start_url = OW_URL_HOME ."dashboard";
            $ret = $this->checkAllLinks($start_url, $CURRENT_SESSIONS, false);
            $this->assertTrue($ret);
        }
    }
    public function testLinksUsers()
    {
        if(true) {
            $test_caption = "linkCheckingTest-testLinksUsers";
            //$this->echoText($test_caption);
            $this->url(OW_URL_HOME); //required for sessions
            $CURRENT_SESSIONS = $this->prepareSession();
            $CURRENT_SESSIONS->currentWindow()->maximize();
            $start_url = OW_URL_HOME ."users";
            $ret = $this->checkAllLinks($start_url, $CURRENT_SESSIONS, false);//true
            $this->assertTrue($ret);
        }
    }
    public function testLinksPhoto()
    {
        if(true) {
            $test_caption = "linkCheckingTest-testLinksPhoto";
            //$this->echoText($test_caption);
            $this->url(OW_URL_HOME); //required for sessions
            $CURRENT_SESSIONS = $this->prepareSession();
            $CURRENT_SESSIONS->currentWindow()->maximize();
            $start_url = OW_URL_HOME ."photo/viewlist/latest";
            $ret = $this->checkAllLinks($start_url, $CURRENT_SESSIONS, true);
            $this->assertTrue($ret);
        }
    }
    public function testLinksRules()
    {
        if(true) {
            $test_caption = "linkCheckingTest-testLinksRules";
            //$this->echoText($test_caption);
            $this->url(OW_URL_HOME); //required for sessions
            $CURRENT_SESSIONS = $this->prepareSession();
            $CURRENT_SESSIONS->currentWindow()->maximize();
            $start_url = OW_URL_HOME ."rules";
            $ret = $this->checkAllLinks($start_url, $CURRENT_SESSIONS, false);//true
            $this->assertTrue($ret);
        }
    }

    /*
    public function testLinksForum()
    {
        if(true) {
            $test_caption = "linkCheckingTest-testLinksForum";
            //$this->echoText($test_caption);
            $this->url(OW_URL_HOME); //required for sessions
            $CURRENT_SESSIONS = $this->prepareSession();
            $CURRENT_SESSIONS->currentWindow()->maximize();
            $start_url = OW_URL_HOME ."forum";
            $ret = $this->checkAllLinks($start_url, $CURRENT_SESSIONS, true);
            $this->assertTrue($ret);
        }
    }
    public function testLinksGroups()
    {
        if(true) {
            $test_caption = "linkCheckingTest-testLinksGroups";
            //$this->echoText($test_caption);
            $this->url(OW_URL_HOME); //required for sessions
            $CURRENT_SESSIONS = $this->prepareSession();
            $CURRENT_SESSIONS->currentWindow()->maximize();
            $start_url = OW_URL_HOME ."groups";
            $ret = $this->checkAllLinks($start_url, $CURRENT_SESSIONS, true);
            $this->assertTrue($ret);
        }
    }
     public function testLinksEvents()
    {
        if(true) {
            $test_caption = "linkCheckingTest-testLinksEvents";
            //$this->echoText($test_caption);
            $this->url(OW_URL_HOME); //required for sessions
            $CURRENT_SESSIONS = $this->prepareSession();
            $CURRENT_SESSIONS->currentWindow()->maximize();
            $start_url = OW_URL_HOME ."events";
            $ret = $this->checkAllLinks($start_url, $CURRENT_SESSIONS, true);
            $this->assertTrue($ret);
        }
    }
    public function testLinksBlogs()
    {
        if(true) {
            $test_caption = "linkCheckingTest-testLinksBlogs";
            //$this->echoText($test_caption);
            $this->url(OW_URL_HOME); //required for sessions
            $CURRENT_SESSIONS = $this->prepareSession();
            $CURRENT_SESSIONS->currentWindow()->maximize();
            $start_url = OW_URL_HOME ."blogs";
            $ret = $this->checkAllLinks($start_url, $CURRENT_SESSIONS, true);
            $this->assertTrue($ret);
        }
    }
    public function testLinksNews()
    {
        if(true) {
            $test_caption = "linkCheckingTest-testLinksNews";
            //$this->echoText($test_caption);
            $this->url(OW_URL_HOME); //required for sessions
            $CURRENT_SESSIONS = $this->prepareSession();
            $CURRENT_SESSIONS->currentWindow()->maximize();
            $start_url = OW_URL_HOME ."news";
            $ret = $this->checkAllLinks($start_url, $CURRENT_SESSIONS, true);
            $this->assertTrue($ret);
        }
    }
    public function testLinksVideo()
    {
        if(true) {
            $test_caption = "linkCheckingTest-testLinksVideo";
            //$this->echoText($test_caption);
            $this->url(OW_URL_HOME); //required for sessions
            $CURRENT_SESSIONS = $this->prepareSession();
            $CURRENT_SESSIONS->currentWindow()->maximize();
            $start_url = OW_URL_HOME ."video";
            $ret = $this->checkAllLinks($start_url, $CURRENT_SESSIONS, false);//true
            $this->assertTrue($ret);
        }
    }
*/



    public function tearDown()
    {
        $questionDao = BOL_QuestionService::getInstance();
        $userDao = BOL_UserDao::getInstance();
        $questionDao->deleteQuestionDataByUserId($this->user1->getId());
        $userDao->deleteById($this->user1->getId());
    }
}