<?php
/**
 * User: Issa Moradnejad
 * Date: 2016/06/01
 */

class iisnewsTest extends IISTestUtilites
{
    private $TEST_USER1_NAME = "user1";
    private $TEST_USER2_NAME = "user2";
    private $TEST_USER3_NAME = "user3";
    private $TEST_PASSWORD = '12345';

    private $userService;
    private $user1,$user2,$user3;

    private $entry1;
    private $entry1_title = "title1";

    private function echoText($text, $bounding_box=false)
    {
        if ($bounding_box) {
            echo "-----------------------------ISSA------------------------------------\n";
            echo "$text\n";
            echo "---------------------------------------------------------------------\n";
        }else
            echo "==========ISSA:==>$text\n";
    }
    private function hide_element($className){
        try {
            $this->execute(array(
                'script' => "document.getElementsByClassName('" . $className . "')[0].style.visibility = 'hidden';",
                'args' => array()
            ));
        }catch(Exception $ex){}
    }

    public function createNews($userID, $title,$text,$tags=array())
    {
        OW::getCacheManager()->clean( array( EntryDao::CACHE_TAG_POST_COUNT ));
        $service = EntryService::getInstance();

        $entry = new Entry();
        $entry->setAuthorId($userID);
        $entry->setTitle($title);
        $entry->setEntry($text);
        $entry->setIsDraft(0);
        $entry->setPrivacy('everybody');
        $entry->setTimestamp(time());

        BOL_AuthorizationService::getInstance()->trackAction('iisnews', 'add_news');
        $service->save($entry);

        //tags
        $tagService = BOL_TagService::getInstance();
        $tagService->updateEntityTags($entry->getId(), 'news-entry', $tags );

        //Newsfeed
        $tagService->setEntityStatus('news-entry', $entry->getId(), true);
        $event = new OW_Event('feed.action', array(
            'pluginKey' => 'iisnews',
            'entityType' => 'news-entry',
            'entityId' => $entry->getId(),
            'userId' => $userID,
        ));
        OW::getEventManager()->trigger($event);
        OW::getEventManager()->trigger(new OW_Event(EntryService::EVENT_AFTER_ADD, array(
            'entryId' => $entry->getId()
        )));
        return $entry;
    }

    protected function setUp()
    {
        $this->setBrowser('firefox');
        $this->setBrowserUrl(OW_URL_HOME);
        $this->userService = BOL_UserService::getInstance();
        $accountType = BOL_QuestionService::getInstance()->getDefaultAccountType()->name;
        IISSecurityProvider::createUser($this->TEST_USER1_NAME,"user1@gmail.com",$this->TEST_PASSWORD,"1987/3/21","1",$accountType);
        IISSecurityProvider::createUser($this->TEST_USER2_NAME,"user2@gmail.com",$this->TEST_PASSWORD,"1987/3/21","1",$accountType);
        IISSecurityProvider::createUser($this->TEST_USER3_NAME,"user3@gmail.com",$this->TEST_PASSWORD,"1987/3/21","1",$accountType);
        $this->user1 = BOL_UserService::getInstance()->findByUsername($this->TEST_USER1_NAME);
        $this->user2 = BOL_UserService::getInstance()->findByUsername($this->TEST_USER2_NAME);
        $this->user3 = BOL_UserService::getInstance()->findByUsername($this->TEST_USER3_NAME);
        // set some info to users

        $friendsQuestionService = FRIENDS_BOL_Service::getInstance();
        $friendsQuestionService->request($this->user1->getId(),$this->user2->getId());
        $friendsQuestionService->accept($this->user2->getId(),$this->user1->getId());

        $this->entry1 = $this->createNews($this->user1->getId(), $this->entry1_title,'<p>Some Text!</p>');
    }

    public function setUpPage()
    {
        parent::setUpPage(); // TODO: Change the autogenerated stub
        $this->timeouts()->implicitWait(15000);
    }

    public function testNews1()
    {
        //----SCENARIO 1 - Seminar
        //admin publishes news.
        //guest can read, can't comment
        //User2 can read. comments on the news

        $test_caption = "iisnewsTest-testNews1";
        //$this->echoText($test_caption);
        $CURRENT_SESSIONS = $this->prepareSession();
        $CURRENT_SESSIONS->currentWindow()->maximize();

        //--------GUEST
        $this->url(OW_URL_HOME . 'news/'.$this->entry1->id);
        $this->hide_element('demo-nav');
        //check if title is the same
        $res = $this->checkIfXPathExists('//h1[contains(@class,"ow_stdmargin ow_ic_write") and contains(text(),"'.$this->entry1_title.'")]');
        $this->assertTrue($res);
        //check if can comment
        $res = $this->checkIfXPathExists('//*[@class="ow_comments_input"]');
        $this->assertTrue(!$res);


        //----------USER2
        $sessionId = $CURRENT_SESSIONS->cookie()->get(OW_Session::getInstance()->getName());
        $sessionId = str_replace('%2C', ',', $sessionId);
        $this->sign_in($this->user2->getUsername(),$this->TEST_PASSWORD,true,true,$sessionId);
        try {
            $this->url(OW_URL_HOME . 'news/'.$this->entry1->id);
            $this->hide_element('demo-nav');

            //check if title is the same
            $res = $this->checkIfXPathExists('//h1[contains(@class,"ow_stdmargin ow_ic_write") and contains(text(),"'.$this->entry1_title.'")]');
            $this->assertTrue($res);

            //check if can comment
            $res = $this->checkIfXPathExists('//*[@class="ow_comments_input"]');
            $this->assertTrue($res);
        } catch (Exception $ex) {
            $this->echoText($ex, true);
            if (getenv("SNAPSHOT_DIR"))
                file_put_contents(getenv("SNAPSHOT_DIR") . $test_caption . '.png', $this->currentScreenshot());
            $this->assertTrue(false);
        }


    }


    public function tearDown()
    {
        //delete news
        EntryService::getInstance()->deleteEntry($this->entry1->getId());

        //delete users
        $questionDao = BOL_QuestionService::getInstance();
        $userDao = BOL_UserDao::getInstance();
        $friendsQuestionService = FRIENDS_BOL_Service::getInstance();

        $friendsQuestionService->deleteUserFriendships($this->user1->getId());
        $questionDao->deleteQuestionDataByUserId($this->user1->getId());
        $userDao->deleteById($this->user1->getId());

        $questionDao->deleteQuestionDataByUserId($this->user2->getId());
        $userDao->deleteById($this->user2->getId());

        $questionDao->deleteQuestionDataByUserId($this->user3->getId());
        $userDao->deleteById($this->user3->getId());
    }
}